### ISSUE TITLE
no release (APK or Fdroid)

### ISSUE THREAD

**Issue by Linkinsoldier** [Atomhoernchen87/Sauspiel-Fan-Client#1]
Could you please put this into fdroid store? Would be nice for the whole community and might lead for more people to use the fdroid store and push open source!

**Comment by Atomhoernchen87** [comment]
I'm gonna try to get it up at fdroid. Never done that before, so it may take a while. Thx

**Comment by Linkinsoldier** [comment]
Would be awesome, thanks!

**Comment by Linkinsoldier** [comment]
APK releases!
